"""Add 'entered' and 'last_edited' to Rule

Revision ID: 36ba7b73f8be
Revises: 
Create Date: 2024-10-22 13:01:11.460133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ba7b73f8be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entered', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('last_edited', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rule', schema=None) as batch_op:
        batch_op.drop_column('last_edited')
        batch_op.drop_column('entered')

    # ### end Alembic commands ###
